### ISSUE TITLE
Resultados do QD são do dia anterior

### ISSUE THREAD

**Issue by augusto-herrmann** [economiagovbr/Ro-dou#26]
Os relatórios enviados pelo Ro-DOU estão enviando resultados do dia atual quando se trata do Diário Oficial da União. Todavia, para os resultados do Querido Diário, sempre (ou quase sempre) são resultados do diário oficial do município do dia anterior.

**Comment by nitaibezerra** [comment]
Isso mesmo. Eu implementei com um dia de delay após analisar e perceber que nem todas as cidades estão coletadas no horário (~5AM) que o Ro-dou coleta. No email resultante a data de cada registro está correta.

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Enviado via Proton Mail para dispositivos móveis

-------- Mensagem Original --------
Em 3 de fev de 2023 15:40, Augusto Herrmann escreveu:

**Comment by augusto-herrmann** [comment]
Entendi. Então era para ser assim, mesmo.

De fato, no e-mail com o relatório, está informado que a data é do dia anterior. Embora esteja em um formato diferente: YYYY-MM-DD, em vez do DD/MM/AAAA usado nos resultados do D.O.U.

**Comment by augusto-herrmann** [comment]
Registrei essa questão em outra issue #28 e estou encerrando esta.
