### ISSUE TITLE
Mostrar informações úteis na descrição de cada dag gerada

### ISSUE THREAD

**Issue by augusto-herrmann** [economiagovbr/Ro-dou#27]
O Airflow oferece a possibilidade de incluir uma descrição da DAG em formato markdown, ao utilizar o parâmetro `doc_md` da DAG.

Atualmente, as DAGs geradas pelo Ro-DOU não têm nenhuma descrição.

A descrição da DAG deveria incluir:
* um texto em markdown, em parâmetro a ser incluído no esquema do arquivo de configuração yaml
* o nome do arquivo de configuração yaml utilizado para configurar a DAG
* o conteúdo da configuração yaml, exceto a descrição acima e possivelmente outros, em bloco de código formatado yaml

A ideia é facilitar para quem está olhando a interface do Airflow poder saber a configuração daquela DAG sem ter que procurar no repositório o conteúdo do yaml. E, se precisar mexer no yaml, também já saberá o nome do arquivo que terá que procurar.

**Comment by nitaibezerra** [comment]
Ótima ideia!

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Enviado via Proton Mail para dispositivos móveis

-------- Mensagem Original --------
Em 3 de fev de 2023 15:47, Augusto Herrmann escreveu:
