### ISSUE TITLE
Pesquisa por termos em um banco de daqdos não funciona

### ISSUE THREAD

**Issue by augusto-herrmann** [economiagovbr/Ro-dou#38]
Após a implementação de #33, a pesquisa por termos lidos de um banco de dados passou a não mais funcionar. Como não há testes que verifiquem essa situação (#37), foi feito o merge do PR #34.

No entanto, ainda é necessário corrigir a busca nos diários oficiais para dags definidas nessa situação.

**Comment by edulauer** [comment]
De acordo!
