### ISSUE TITLE
Broken plugin: [/opt/airflow/plugins/FastETL/custom_functions/patchwork.py] No module named 'FastETL.hooks.gsheet_hook'

### ISSUE THREAD

**Issue by dasmoscas** [economiagovbr/Ro-dou#43]
Boa tarde a todos,

Agradeço pela disponibilização do programa Ro-dou, o qual tem o potencial de solucionar alguns problemas técnicos em nosso ambiente. Após a conclusão do processo de instalação, a página inicial do Airflow é apresentada ao acessar o endereço "localhost:8080", exibindo corretamente os DAGs. No entanto, é exibida em destaque a mensagem "_Broken plugin: [/opt/airflow/plugins/FastETL/custom_functions/patchwork.py] No module named 'FastETL.hooks.gsheet_hook_'" em vermelho no topo da tela. Apesar disso, a funcionalidade de pesquisa parece operar normalmente, porém apresenta falhas ao enviar dados (provavelmente devido a questões de configuração do servidor de e-mail, as quais estão sendo investigadas).

Destaco que a instalação do programa Ro-dou está sendo realizada em ambiente Debian 11 com a utilização do docker-compose na versão 2.16.0.

Gostaria de saber se é possível ignorar a mensagem de erro mencionada anteriormente ou se há alguma sugestão para resolvê-la.

Agradeço antecipadamente pela atenção e colaboração.
**docker-compose.yml:**
    `version:` '3'
    x-airflow-common:
      &airflow-common
      image: ghcr.io/economiagovbr/airflow2-docker:latest
      environment:
        &airflow-common-env
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
        AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'true'
        AIRFLOW__CORE__FERNET_KEY: 'Uqv6pwYWJn7xifR3QAkifMTkupos8mkxaQL2Q7Ydsqw='
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
        AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
        AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
        AIRFLOW__CORE__DEFAULT_TIMEZONE: 'America/Sao_Paulo'
        AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: 'America/Sao_Paulo'
        AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_RETRY: 'false'
        AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_FAILURE: 'false'
        AIRFLOW__WEBSERVER__SECRET_KEY: '42'
        AIRFLOW__WEBSERVER__WORKERS: 1

        _AIRFLOW_DB_UPGRADE: 'true'
        _AIRFLOW_WWW_USER_CREATE: 'true'
        _AIRFLOW_WWW_USER_USERNAME: airflow
        _AIRFLOW_WWW_USER_PASSWORD: airflow

        AIRFLOW__SMTP__SMTP_HOST: email-ssl.com.br
        AIRFLOW__SMTP__SMTP_USER: alertas@funag.gov.br
        AIRFLOW__SMTP__SMTP_PASSWORD: xxxx
        AIRFLOW__SMTP__SMTP_STARTTLS: 'true'
        AIRFLOW__SMTP__SMTP_PORT: 465
        AIRFLOW__SMTP__SMTP_MAIL_FROM: alertas@funag.gov.br

        AIRFLOW_CONN_EXAMPLE_DATABASE_CONN: postgresql://airflow:airflow@postgres:5432/airflow
      volumes:
        - ./src:/opt/airflow/dags/ro_dou
        - ./dag_confs:/opt/airflow/dags/ro_dou/dag_confs
        - ./tests:/opt/airflow/tests

        - ./FastETL/hooks/dou_hook.py:/opt/airflow/plugins/FastETL/hooks/dou_hook.py
        - ./FastETL/custom_functions:/opt/airflow/plugins/FastETL/custom_functions
      depends_on:
        postgres:
          condition: service_healthy

    services:
      postgres:
        image: postgres:13
        environment:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        volumes:
          - ./mnt/pgdata:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD", "pg_isready", "-U", "airflow"]
          interval: 5s
          retries: 5
        restart: always

      airflow-webserver:
        <<: *airflow-common
        container_name: airflow-webserver
        command: webserver
        ports:
          - 8080:8080
        healthcheck:
          test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
          interval: 10s
          timeout: 10s
          retries: 5
        restart: always

      airflow-scheduler:
        <<: *airflow-common
        container_name: airflow-scheduler
        command: scheduler
        restart: always

      smtp4dev:
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
          - '5000:80'
          - '25:25' # Change the number before : to the port the SMTP server should be accessible on
          - '143:143' # Change the number before : to the port the IMAP server should be accessible on
        volumes:
            - smtp4dev-data:/smtp4dev
        environment:
          - ServerOptions__HostName=smtp4dev

      # selenium:
      #     image: ghcr.io/economiagovbr/selenium:ro-dou
      #     volumes:
      #       - /dev/shm:/dev/shm
    volumes:
      smtp4dev-data:`
**all_parameters_example.yaml:**
dag:

  id: all_parameters_example

  description: DAG exemplo utilizando todos os demais parâmetros.

  tags:

    - projeto_a

    - departamento_x

  schedule: 0 8 * * MON-FRI

  search:

    terms:

    - Analista de Tecnologia da Informação

    - ATI

    field: TUDO

    is_exact_search: On

    ignore_signature_match: On

    force_rematch: On

    date: MES

    dou_sections:

      - SECAO_1

      - EDICAO_SUPLEMENTAR

  report:

    emails:

      - xxx@funag.gov.br

      - xxx@gmail.com

    attach_csv: True

    subject: Ro-DOU - Analista de Tecnologia da Informação

**Comment by augusto-herrmann** [comment]
Obrigado pelo relato detalhado, @dasmoscas!

De fato, o problema é causado porque o `docker-compose.yml` atual, na hora de montar os volumes, carrega somente o `dou_hook.py` do pacote FastETL na pasta `hooks`. Por outro lado, carrega todo o módulo `custom_functions` e alguns desses módulos fazem referência aos demais hooks.

O problema não afeta o funcionamento do Ro-DOU porque está numa parte do FastETL que não é utilizada pelo Ro-DOU, então não se preocupe.

Mesmo assim, iremos corrigir.
