### ISSUE TITLE
Integrar o Ro-dou ao Querido Diário

### ISSUE THREAD

**Issue by nitaibezerra** [economiagovbr/Ro-dou#9]
O [Querido Diário](https://queridodiario.ok.org.br/) é uma plataforma que indexa e permite a busca em diversos diários oficiais de estados e municípios. A integração com ele ampliará o alcance do Ro-dou para além do Diário Oficial da União. O QD possui uma [API pública](https://queridodiario.ok.org.br/api/docs) que pode ser utilizada para esta integração.

**Comment by augusto-herrmann** [comment]
@nitaibezerra, a integração referenciada nessa issue é a que já foi implementada e podemos fechá-la, certo?

**Comment by nitaibezerra** [comment]
Exatamente. Eu esqueci de fazer a correlação no PR.

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Enviado via Proton Mail para dispositivos móveis

-------- Mensagem Original --------
Em 3 de fev de 2023 15:38, Augusto Herrmann escreveu:

**Comment by augusto-herrmann** [comment]
Implementado pelo PR #14.
